apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-manager
  namespace: default
spec:
  selector:
    matchLabels:
      app: trident-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: trident-manager
    spec:
      containers:
        - name: manager
          image: k8scloudplatform/trident:latest
          imagePullPolicy: Always
      serviceAccountName: trident-manager